name: Docker Image CI

on:
  create:
    tags:
      - v*
      
env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    environment: main

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.3.0
      with:
        tags: goodenberg:${{ github.event.release.tag_name }}
